- name: Launching an instance using ansible.
  hosts: localhost
  gather_facts: no  
  become: yes
  roles:
    - ec2_launch

  vars:
    ansible_ssh_private_key_file: "/home/shahna7771/Public/AwsKey/awsKey.pem"
    ansible_user: ec2-user"

  tasks:
    - name: Install Apache on dynamically added EC2
      become: yes
      package:
        name: httpd
        state: present
      delegate_to: "{{ item }}"
      with_items: "{{ groups['dynamic_hosts'] }}"
      when: groups['dynamic_hosts'] is defined and groups['dynamic_hosts'] | length > 0

    - name: Start Apache service on EC2
      become: true
      service:
        name: httpd
        state: started
        enabled: yes
      delegate_to: "{{ item }}"
      with_items: "{{ groups['dynamic_hosts'] }}"
      when: groups['dynamic_hosts'] is defined and groups['dynamic_hosts'] | length > 0
